Dto for CoursesController and an example of its mapping
whereismyroot/WhatBackend pull request #37
Opened 2020-10-27 13:50 UTC by BohdanBBG

2020-10-27 16:11 UTC, SerjKocherga requested changes
``

2020-10-27 16:11 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
Add to return Ok(createdCourse) above.

2020-10-28 09:15 UTC, whereismyroot requested changes
needs some changes

2020-10-28 09:15 UTC, whereismyroot commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +            }
You don't need to use mapper in controller. As suggested in previous comments, please leave only dto or model

2020-10-28 09:15 UTC, whereismyroot commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +            var createdCourse = await _coursesService.CreateCourseAsync(_mapper.Map<CreateCourseModel>(courseDto));
You don't need to use mapper in controller. As suggested in previous comments, please leave only dto or model

2020-10-28 10:36 UTC, SerjKocherga approved these changes

2020-10-28 11:42 UTC, whereismyroot approved these changes

2020-10-28 11:42 UTC, whereismyroot commented on CharlieBackend.Business/Services/Interfaces/ICourseService.cs
> +        public Task<CreateCourseDto> CreateCourseAsync(CreateCourseDto courseModel);
This method should return CourseDto

2020-10-28 11:42 UTC, whereismyroot commented on CharlieBackend.Business/Services/Interfaces/ICourseService.cs
> +        public Task<UpdateCourseDto> UpdateCourseAsync(long id, UpdateCourseDto courseModel);
This method should return CourseDto

2020-10-28 11:42 UTC, whereismyroot commented on CharlieBackend.Core/AdapterExtensionMethods.cs
> +        //}
Please remove this

2020-10-28 11:42 UTC, whereismyroot commented on CharlieBackend.Core/AdapterExtensionMethods.cs
> +        //}
Please remove this

2020-10-28 13:19 UTC, merged