Fixed update issue in UpdateStudentGroup method
whereismyroot/WhatBackend pull request #61
Opened 2020-11-02 10:02 UTC by BohdanBBG

2020-11-02 12:53 UTC, SerjKocherga requested changes

2020-11-02 12:53 UTC, SerjKocherga commented on CharlieBackend.Business/Services/StudentGroupService.cs
> -                        });
Add new line before return.

2020-11-02 14:52 UTC, Vlad1023 commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +                return _mapper.Map<UpdateStudentGroupDto>(updatedEntity);
What about using Result<T> ?

2020-11-02 15:25 UTC, SerjKocherga approved these changes

2020-11-03 08:55 UTC, sober607 approved these changes

2020-11-03 11:42 UTC, BohdanBBG commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +                return _mapper.Map<UpdateStudentGroupDto>(updatedEntity);
Done

2020-11-03 11:46 UTC, merged