Feature/secretary controller
whereismyroot/WhatBackend pull request #62
Opened 2020-11-02 11:11 UTC by x1mx1x

2020-11-02 11:37 UTC, SerjKocherga requested changes

2020-11-02 11:37 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/SecretariesController.cs
> +            return Ok(new { createdSecretaryDto.Id });
Return a created model.

2020-11-02 11:37 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/SecretariesController.cs
> +        public async Task<ActionResult> updateSecretary(long id, UpdateSecretaryDto secretaryDto)
Rename to UpdateSecretary.

2020-11-02 11:37 UTC, SerjKocherga commented on CharlieBackend.Business/Services/SecretaryService.cs
> +
Remove this new line.

2020-11-02 11:37 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/SecretaryRepository.cs
> +
Remove this empty lines.

2020-11-02 11:37 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/SecretaryRepository.cs
> +
39 and 40 lines also should be removed.

2020-11-02 14:27 UTC, SnipeFrost approved these changes
good

2020-11-02 14:28 UTC, SerjKocherga approved these changes

2020-11-02 14:45 UTC, merged

2020-11-03 08:42 UTC, sober607 reviewed
Small change recommended

2020-11-03 08:42 UTC, sober607 commented on CharlieBackend.Business/Services/SecretaryService.cs
> +                    Console.WriteLine("Debug info exception details: " + ex);
This is for debug stage only