Feature/add registration
whereismyroot/WhatBackend pull request #84
Opened 2020-11-04 21:45 UTC by SnipeFrost

1. Created enum for roles and changed DTO's and Controllers for using enum
2. Created DTO's for AccountsController and theirs mapping
3. Created DTO's for Mentors and Students controllers and theirs mapping
4. Created registration
5. Reworked Mentors and Students controllers and services for using new Accounts Dto

2020-11-05 09:43 UTC, x1mx1x approved these changes

2020-11-05 10:16 UTC, SerjKocherga requested changes

2020-11-05 12:58 UTC, Vlad1023 commented on CharlieBackend.Api/Controllers/StudentsController.cs
> +        public async Task<ActionResult> PostStudent(long id)
is it accountId here ?

2020-11-05 20:20 UTC, SnipeFrost commented on CharlieBackend.Api/Controllers/AccountsController.cs
> +                return StatusCode(403, foundAccount.Email + " is registered and waiting assign.");
I dont know why its like this here when in VS its good

2020-11-05 21:34 UTC, SerjKocherga approved these changes

2020-11-06 08:37 UTC, sober607 approved these changes

2020-11-06 10:34 UTC, merged